# values.yaml for darthdataditch Helm chart
#Service account
serviceAccount:
  create: true
  name: darthdataditch

# Application configurations
replicaCount: 2
image:
  repository: 433663489437.dkr.ecr.eu-central-1.amazonaws.com/darthdataditch-ecr
  tag: 0.0.4
  pullPolicy: Always

# Service configurations
service:
  type: ClusterIP
  port: 8000

# Ingress configurations
ingress:
  enabled: true
  annotations: {}
  host: us.darthdataditch.jftr.info
  path: /
  subnets:
    - subnet-080c103c8fe171b8c
    - subnet-065073ac3d96f6fb5
  eipId: eipalloc-06636ee36ce973e25

# ACM Certificate ARN for HTTPS
acmCertificateArn: arn:aws:acm:us-east-1:433663489437:certificate/fa722073-69d2-430a-8620-2b8172ea3dff

# Pod configurations
pod:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::433663489437:role/eks-node-role

# Resource requests and limits
resources: 
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: 
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - darthdataditch
        topologyKey: "kubernetes.io/hostname"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env:
  S3_BUCKET_NAME: holocron-archives

# debug
containerCommand: ["/bin/bash"]
containerArgs: ["-c", "sleep 3600"]