# values.yaml for darthdataditch Helm chart
#Service account
serviceAccount:
  create: true
  name: darthdataditch

# Application configurations
replicaCount: 2
image:
  repository: 433663489437.dkr.ecr.eu-central-1.amazonaws.com/darthdataditch-ecr
  tag: 
  pullPolicy: Always
env:
  S3_BUCKET_NAME: holocron-archives
  APP_VERSION:
  USER_TOKENS: "jedi:$2b$12$SnqqC0wiU/ovEoYcmIjEFOadmb06f5Vh7vmvqxQSStvmGxtn9QnCa"
