# values.yaml for darthdataditch Helm chart
#Service account
serviceAccount:
  create: true
  name: darthdataditch

# Application configurations
replicaCount: 2
image:
  repository: 433663489437.dkr.ecr.eu-central-1.amazonaws.com/darthdataditch-ecr
  tag: prod
  pullPolicy: Always

# Service configurations
service:
  type: ClusterIP
  port: 8000

# Ingress configurations
ingress:
  enabled: true
  annotations: {}
  host: us.darthdataditch.jftr.info
  path: /*
  subnets:
    - subnet-04e7e1c50330691b9
    - subnet-0c64e9a8e971bf505
  eipId: eipalloc-0a49677f3bc4b131a

# ACM Certificate ARN for HTTPS
acmCertificateArn: arn:aws:acm:us-east-1:433663489437:certificate/bdf01c71-17c2-4ce7-9d76-57b0f45599ff

# Pod configurations
pod:
  annotations: {}

# Resource requests and limits
resources: 
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: 
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - darthdataditch
        topologyKey: "kubernetes.io/hostname"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env:
  S3_BUCKET_NAME: holocron-archives

# debug
containerCommand: ["/bin/bash"]
containerArgs: ["-c", "sleep 3600"]
